#!/bin/bash
# 🚀 setup-github-auto.sh
# Автоматически создаёт новый GitHub репозиторий через API + пушит через SSH.
# Работает без gh CLI.
# Требуется GITHUB_TOKEN (Personal Access Token с правами `repo`).

set -e

# === НАСТРОЙКИ ===
GITHUB_HOST="github-work"  # твой SSH alias (см. ~/.ssh/config)
USERNAME=""                 # можно оставить пустым — определится по API
REPO_NAME=""
DESCRIPTION="Autogenerated repository"
PRIVATE=false
CLEAN=false

# === ПАРСИНГ ПАРАМЕТРОВ ===
while [[ "$#" -gt 0 ]]; do
  case $1 in
    --name) REPO_NAME="$2"; shift ;;
    --desc) DESCRIPTION="$2"; shift ;;
    --private) PRIVATE=true ;;
    --clean) CLEAN=true ;;
    *) echo "⚠️ Неизвестный параметр: $1" ;;
  esac
  shift
done

# === ПРОВЕРКИ ===
if [ -z "$GITHUB_TOKEN" ]; then
  echo "❌ Не задан GITHUB_TOKEN (Personal Access Token)."
  echo "👉 Создай токен с правами repo и задай: export GITHUB_TOKEN=your_token"
  exit 1
fi

if [ -z "$REPO_NAME" ]; then
  echo "❌ Укажи имя репозитория: --name my-repo"
  exit 1
fi

# === SSH-ДОСТУП ===
echo "🔍 Проверяю SSH-доступ к $GITHUB_HOST..."
if ! ssh -T "$GITHUB_HOST" 2>&1 | grep -q "successfully authenticated"; then
  echo "⚠️ SSH-доступ к $GITHUB_HOST не настроен. Проверь ~/.ssh/config и ключи."
  exit 1
fi

# === CLEAN MODE ===
if [ "$CLEAN" = true ]; then
  echo "🧹 Очистка старого репозитория..."
  rm -rf .git
  git init
else
  [ ! -d .git ] && git init
fi

# === ОПРЕДЕЛЯЕМ ИМЯ ПОЛЬЗОВАТЕЛЯ ЧЕРЕЗ API ===
echo "👤 Определяю имя пользователя..."
USERNAME=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user | jq -r .login)
if [ -z "$USERNAME" ] || [ "$USERNAME" = "null" ]; then
  echo "❌ Не удалось определить имя пользователя. Проверь GITHUB_TOKEN."
  exit 1
fi

# === СОЗДАНИЕ РЕПОЗИТОРИЯ ===
echo "📦 Создаю репозиторий '$REPO_NAME' от имени $USERNAME..."
CREATE_PAYLOAD=$(jq -n \
  --arg name "$REPO_NAME" \
  --arg desc "$DESCRIPTION" \
  --argjson private $PRIVATE \
  '{name: $name, description: $desc, private: $private}')

CREATE_RESPONSE=$(curl -s -X POST \
  -H "Authorization: token $GITHUB_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/user/repos \
  -d "$CREATE_PAYLOAD")

if echo "$CREATE_RESPONSE" | grep -q '"message": "name already exists"'; then
  echo "⚠️ Репозиторий $REPO_NAME уже существует — продолжаем пуш."
else
  echo "✅ Репозиторий создан!"
fi

# === GIT REMOTE ===
REMOTE_URL="$GITHUB_HOST:$USERNAME/$REPO_NAME.git"

git add .
git commit -m "Initial commit" || true
git branch -M main

git remote remove origin 2>/dev/null || true
git remote add origin "$REMOTE_URL"

echo "📤 Пушим в $REMOTE_URL ..."
git push -u origin main

echo "✅ Успешно! Репозиторий доступен по ссылке:"
echo "🔗 https://github.com/$USERNAME/$REPO_NAME"
